### ISSUE TITLE
Your package is awesome

### ISSUE THREAD

**Issue by lordnynex** [mmaelzer/cam#1]
Moved into a new place and am having some issues with the wildlife. Using some cheap ipcams, to figure out whats going on before I can finish unpacking the dvr/cam system. I just wanted to drop you a line and share what your package helped me capture tonight! This package would be awesome with some additional features to collapse the frames or something. 

http://i.imgur.com/p1JpSy5.gif

**Comment by mmaelzer** [comment]
Thank you! It always makes me happy knowing someone found something I wrote useful. As someone that grew up in Appalachia, I love the fact that you caught a black bear dumpster diving.

Regarding collapsing frames (and other features), I did create a simple motion detection package in Go as well: https://github.com/mmaelzer/camotion. That would allow you to easily discard frames when nothing is happening.

At home, I run my opencam project on a Raspberry Pi for home security: https://github.com/mmaelzer/opencam

Opencam uses both cam and camotion along with a simple http server and web-based client.

Sadly, I've yet to write good documentation for opencam, but the gist of it is, run a [sqld](https://github.com/mmaelzer/sqld) server (sqllite is the only db type supported in opencam), then start opencam and add a camera via the config webpage.

Thank you so much for sharing your success with this package.
